import type { NextPage } from "next";
import LegalDocumentTemplate from "@/templates/LegalCompliancePage/LegalDocumentTemplate";

const CookiePolicy: NextPage = () => {
    return (
        <LegalDocumentTemplate 
            title="Cookie Policy"
            lastUpdated="June 19, 2025"
        >
            <h5>1. Introduction</h5>
            <p>
                This Cookie Policy explains how Dugong Global Services Pvt Ltd ("Dugong," "we," "us," or "our"), operating the project known as "Dharitri," uses cookies and similar tracking technologies on our website [YourWebsiteAddress.com] (the "Website") and our staking platform at stake.dharitri.org (the "Staking Platform"). It describes what these technologies are, why we use them, and your rights to control our use of them.
            </p>
            <p>
                This Cookie Policy should be read in conjunction with our [Link to Your Privacy Policy Page] ("Privacy Policy"), which provides more detailed information about our data processing practices.
            </p>
            <p>
                We strive to comply with applicable data protection laws, including GDPR requirements for European users and other international standards for cookie usage.
            </p>

            <h5>2. What Are Cookies?</h5>
            <p>
                Cookies are small text files that are placed on your computer or mobile device by websites that you visit. They are widely used to make websites work, or work more efficiently, as well as to provide information to the owners of the site.
            </p>
            <p>
                Cookies can be "session" cookies (which are deleted once you close your web browser) or "cookies that stay until you delete them" (also called "persistent" cookies). They can also be "first-party" cookies (set by the website you are visiting, i.e., by Dugong for the Dharitri Website) or "third-party" cookies (set by a domain other than the one you are visiting, e.g., by Google Analytics).
            </p>

            <h5>3. How and Why We Use Cookies</h5>
            <p>
                Dugong uses cookies on the Dharitri Website and Staking Platform for several reasons:
            </p>
            <ul>
                <li>To ensure our Website and Staking Platform function correctly and securely</li>
                <li>To understand how our services are used, which helps us improve performance and user experience</li>
                <li>To remember your preferences (such as your cookie consent choices and wallet connections)</li>
                <li>To remember your staking preferences and transaction history on our Staking Platform</li>
                <li>To provide enhanced security through CSRF protection and session management</li>
            </ul>

            <h5>4. Types of Cookies We Use</h5>
            <p>
                We use the following types of cookies on the Dharitri Website and Staking Platform:
            </p>

            <h5>4.1 Strictly Necessary Cookies</h5>
            <p>
                <strong>Purpose:</strong> These cookies are essential for you to browse the Website and Staking Platform and use their core features, such as navigating between pages, managing your cookie consent preferences, connecting wallets, and submitting forms. Strictly necessary cookies include CSRF tokens to prevent form hijacking – disabling them breaks form submissions and wallet connections.
            </p>
            <p>
                <strong>Consent:</strong> These cookies do not require your consent as they are essential for the operation of our services.
            </p>
            <p>
                <strong>Examples:</strong>
            </p>
            <ul>
                <li>Cookies used to remember your cookie consent status</li>
                <li>Session cookies for website and staking platform security</li>
                <li>Wallet connection state cookies</li>
                <li>Form security tokens</li>
            </ul>

            <h5>4.2 Performance and Analytics Cookies</h5>
            <p>
                <strong>Purpose:</strong> These cookies collect information about how you use our Website and Staking Platform, such as which pages you visit most often, how much time you spend on those pages, staking activity patterns, and if you encounter any error messages. The information collected is typically aggregated and anonymous and helps us improve how our services work.
            </p>
            <p>
                <strong>Google Analytics:</strong> We use Google Analytics, a web analytics service provided by Google, Inc. ("Google"). Google Analytics uses cookies to help us analyze how users use the Website and Staking Platform. The information generated by the cookie about your use of our services (including your IP address, which is anonymized) will be transmitted to and stored by Google on servers that may be located outside of your country of residence. Google will use this information for the purpose of evaluating your use of our services, compiling reports on activity for us, and providing other services relating to website activity and internet usage.
            </p>
            <p>
                You can learn more about Google's practices by going to https://policies.google.com/privacy/partners/, and opt-out of them by downloading the Google Analytics opt-out browser add-on, available at https://tools.google.com/dlpage/gaoptout.
            </p>
            <p>
                <strong>Consent:</strong> We will only place these cookies on your device if you give us your consent through our cookie consent banner.
            </p>

            <h5>5. Third-Party Cookies and Services</h5>
            <p>
                Please note that some cookies on our Website and Staking Platform may be placed by third-party services that appear on our pages or are necessary for functionality:
            </p>

            <h5>Cookie Summary Table</h5>
            <div className="overflow-x-auto mt-4 mb-6">
                <table className="w-full border-collapse border border-greyscale-200 dark:border-dark-border">
                    <thead>
                        <tr className="bg-greyscale-50 dark:bg-dark-card">
                            <th className="border border-greyscale-200 dark:border-dark-border p-3 text-left">Provider</th>
                            <th className="border border-greyscale-200 dark:border-dark-border p-3 text-left">Cookie Type</th>
                            <th className="border border-greyscale-200 dark:border-dark-border p-3 text-left">Purpose</th>
                            <th className="border border-greyscale-200 dark:border-dark-border p-3 text-left">Duration</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td className="border border-greyscale-200 dark:border-dark-border p-3">Google Analytics</td>
                            <td className="border border-greyscale-200 dark:border-dark-border p-3">Performance</td>
                            <td className="border border-greyscale-200 dark:border-dark-border p-3">Traffic analysis and user behavior</td>
                            <td className="border border-greyscale-200 dark:border-dark-border p-3">14 months</td>
                        </tr>
                        <tr className="bg-greyscale-25 dark:bg-dark-card-subtle">
                            <td className="border border-greyscale-200 dark:border-dark-border p-3">Tally.so</td>
                            <td className="border border-greyscale-200 dark:border-dark-border p-3">Strictly Necessary</td>
                            <td className="border border-greyscale-200 dark:border-dark-border p-3">Contact form functionality</td>
                            <td className="border border-greyscale-200 dark:border-dark-border p-3">Session</td>
                        </tr>
                        <tr>
                            <td className="border border-greyscale-200 dark:border-dark-border p-3">HostArmada</td>
                            <td className="border border-greyscale-200 dark:border-dark-border p-3">Strictly Necessary</td>
                            <td className="border border-greyscale-200 dark:border-dark-border p-3">Server security and load balancing</td>
                            <td className="border border-greyscale-200 dark:border-dark-border p-3">24 hours</td>
                        </tr>
                        <tr className="bg-greyscale-25 dark:bg-dark-card-subtle">
                            <td className="border border-greyscale-200 dark:border-dark-border p-3">Wallet Providers</td>
                            <td className="border border-greyscale-200 dark:border-dark-border p-3">Strictly Necessary</td>
                            <td className="border border-greyscale-200 dark:border-dark-border p-3">Wallet connection state (Staking Platform)</td>
                            <td className="border border-greyscale-200 dark:border-dark-border p-3">Session</td>
                        </tr>
                    </tbody>
                </table>
            </div>

            <h5>Detailed Third-Party Services</h5>
            <ul>
                <li><strong>Google Analytics:</strong> As described above in Section 4.2.</li>
                <li><strong>Tally.so:</strong> Our contact forms provider, which may set cookies necessary for form functionality and security when forms are embedded on our Website. These are considered strictly necessary for form operations.</li>
                <li><strong>HostArmada:</strong> Our website hosting provider, which may set cookies for server security, load balancing, and session management. These are essential for website functionality.</li>
                <li><strong>Wallet Connection Services:</strong> On our Staking Platform (stake.dharitri.org), wallet providers (such as MetaMask, Trust Wallet) may set cookies to maintain connection state and user preferences. These are necessary for staking functionality.</li>
            </ul>
            <p>
                <strong>Important Note:</strong> Dugong does not have direct control over third-party cookies or the information they collect. We recommend that you review the cookie and privacy policies of these third parties for more information about their data practices.
            </p>

            <h5>6. Your Choices and Managing Cookies</h5>
            <p>
                You have several options for controlling and managing cookies:
            </p>

            <h5>Cookie Consent Banner</h5>
            <p>
                When you first visit our Website or Staking Platform, you will be presented with a cookie consent banner. GDPR requires prior consent for non-essential cookies. Our banner enforces this and ensures you can accept or reject non-essential cookies with equal ease, and access to our Website is not blocked if you reject cookies.
            </p>
            <p>
                This banner allows you to accept or reject the use of non-essential cookies (Performance/Analytics cookies). Your preferences will be remembered for future visits, but you can change them at any time through the consent management tool provided on our services.
            </p>
            <p>
                <strong>Withdrawing Consent:</strong> To withdraw consent, use our cookie settings tool or clear your browser cookies. Withdrawing consent requires reloading the page. Essential cookies will reapply automatically to maintain basic functionality.
            </p>

            <h5>Browser Settings</h5>
            <p>
                Most web browsers allow some control of most cookies through the browser settings. You can usually find these settings in the "options" or "preferences" menu of your browser. You can set your browser to block certain cookies, or to alert you when cookies are being sent to your device. You can also delete cookies already stored on your device.
            </p>
            <p>
                To find out more about cookies, including how to see what cookies have been set and how to manage and delete them, visit www.aboutcookies.org or www.allaboutcookies.org.
            </p>

            <h5>Google Analytics Opt-out</h5>
            <p>
                As mentioned above, you can opt-out of Google Analytics tracking by installing the Google Analytics opt-out browser add-on: https://tools.google.com/dlpage/gaoptout.
            </p>

            <h5>Important Limitations</h5>
            <p>
                Please note that if you choose to block or delete cookies, some parts of our Website and Staking Platform may not function properly or may be inaccessible. Disabling strictly necessary cookies will likely impact functionality including:
            </p>
            <ul>
                <li>Form submissions</li>
                <li>Wallet connections on the Staking Platform</li>
                <li>Security features</li>
                <li>User preference settings</li>
            </ul>

            <h5>7. Jurisdictional Considerations</h5>
            <h5>EU Users (GDPR Compliance)</h5>
            <p>
                For users in the European Union, we comply with GDPR requirements for cookie consent. Non-essential cookies are only placed with your explicit consent, and you have the right to withdraw consent at any time.
            </p>

            <h5>Kenya Users (Future Operations)</h5>
            <p>
                Kenyan users may withdraw cookie consent anytime via browser settings or our consent management tool. For data protection concerns, you may contact Kenya's Office of the Data Protection Commissioner (ODPC).
            </p>

            <h5>International Data Transfers</h5>
            <p>
                Cookie data may be processed in:
            </p>
            <ul>
                <li><strong>India:</strong> Where Dugong Global Services Pvt Ltd is located</li>
                <li><strong>Europe:</strong> Where some third-party services store data</li>
                <li><strong>Other locations globally:</strong> Where services like Google Analytics operate</li>
            </ul>

            <h5>8. Cookie Retention Periods</h5>
            <p>
                Different types of cookies are retained for different periods:
            </p>
            <ul>
                <li><strong>Strictly Necessary:</strong> Session cookies (deleted when browser closes) or up to 12 months maximum</li>
                <li><strong>Performance/Analytics:</strong> Up to 14 months (Google Analytics standard retention)</li>
                <li><strong>Wallet Connection:</strong> Session-based (cleared when wallet disconnected)</li>
                <li><strong>Consent Preferences:</strong> Up to 12 months or until manually changed</li>
            </ul>

            <h5>9. Updates and Future Cookies</h5>
            <h5>Changes to This Cookie Policy</h5>
            <p>
                Dugong may update this Cookie Policy from time to time to reflect changes in our practices concerning the Dharitri Website and Staking Platform or for other operational, legal, or regulatory reasons. We will notify you of any changes by posting the new Cookie Policy on this page and updating the "Last Updated" date at the top.
            </p>
            <p>
                <strong>New Cookie Deployment:</strong> Any new cookies will be listed in this policy at least 14 days before deployment, and we will seek appropriate consent where required.
            </p>
            <p>
                We encourage you to review this Cookie Policy periodically for any changes. Changes to this Cookie Policy are effective when they are posted on this page.
            </p>

            <h5>10. Contact Us</h5>
            <p>
                If you have any questions about our use of cookies on the Dharitri Website, Staking Platform, or this Cookie Policy, please contact Dugong Global Services Pvt Ltd:
            </p>
            <p>
                <strong>Email:</strong> privacy@dharitri.org
            </p>
            <p>
                <strong>Mail:</strong><br />
                Dugong Global Services Pvt Ltd<br />
                P&26/P, NAVYA THE GRAND, 1-179/27,<br />
                Patancheru, Rameshwar Banda,<br />
                Hyderabad, Telangana 502319, India
            </p>
            <p>
                For additional information about our data processing practices, please refer to our complete Privacy Policy available at [Link to Your Privacy Policy Page].
            </p>
        </LegalDocumentTemplate>
    );
};

export default CookiePolicy;
